### PR TITLE
Update argparse_to_json.py for FileType actions.

### PR DESCRIPTION
**Pull request by changeling**
Add elif is_file(action) to set widget to FileSaver for FileType actions.
Add is_file() function.
Exclude FileType actions from is_standard().

### CODE REVIEW

**Comment by chriskiehl** [comment]
Ah, nice! Could you re-target this PR against the 1.0.3-release branch?

**Comment by changeling** [comment]
Re-targeted against the 1.0.3-release branch.

(Or rather, done!)

(I notice the version in `setup.py` is set to 1.0.2. Is that intentional until release? Just curious.)

**Comment by changeling** [comment]
Note that this isn't really all that useful while https://github.com/chriskiehl/Gooey/issues/377 is still there. I'm looking at that, but not sure how to best fix the issue without a stronger familiarity with the larger code base. Prolly something better addressed by yourself or someone else more familiar. :)

**Comment by chriskiehl** [comment]
Few things: looks like your upstream merge went a little awry. Checkout the `files changed` and `commits` tabs to see what's up. You'll need to either rebase, or cherry pick your commit onto a fresh branch. 

On `setup.py` currently being 1.0.2 -- nah, not intentional. Just haven't gotten around to updating it yet. I still have a lot of tedious management / version bumping / doc writing / work to do to get the release ready to go. That'll be part of it. 

I just took a look at #377 -- I'll post my comment there (for the sake of organization)

**Pull request closed without merging**
