### PR TITLE
Allow sub parsers recursively

### PR DESCRIPTION
**Pull request by albertoderodrigo**
Improved the iter_parsers function of the argparse_to_json.py to allow the extraction to the sub parser recursively

### CODE REVIEW

**Comment by albertoderodrigo** [comment]
We were testing your awesome lib with our internal tools and we had problems to use it because we have a lot of sub parsers. We where able to use it with this simple fix. 

Let me know if we miss something that we can improve.

**Comment by chriskiehl** [comment]
Change lgtm from a glance. 

Could you give a quick code sample of an argparse setup that this fixes?

**Comment by albertoderodrigo** [comment]
Yeah sure, 

With the following example:

```python
@Gooey
def main():
    parser = argparse.ArgumentParser(description='Dummy example')
    sub_parser = parser.add_subparsers(dest='action', help='Available tools')
    sub_parser.required = True

    a_parser = sub_parser.add_parser('a')
    a_sub_parser = a_parser.add_subparsers(dest='action')
    a_sub_parser.required = True

    aa_parser = a_sub_parser.add_parser('aa')

    aa_sub_parser = aa_parser.add_subparsers(dest='action')
    aa_sub_parser.required = True

    aaa_parser = aa_sub_parser.add_parser('aaa')
    aaa_parser.add_argument('test', type=str)

    aab_parser = aa_sub_parser.add_parser('aab')
    aab_parser.add_argument('test', type=str)

    ab_parser = a_sub_parser.add_parser('ab')

    ab_sub_parser = ab_parser.add_subparsers(dest='action')
    ab_sub_parser.required = True

    aba_parser = aa_sub_parser.add_parser('aba')
    aba_parser.add_argument('test', type=str)

    args = parser.parse_args(sys.argv)
    print(args)
```

Before the fix you get:

image

And after the fix:

image

**Comment by chriskiehl** [comment]
Hey @albertoderodrigo, I had to revert this in the 1.0.4 branch. I didn't check it thoroughly before merging and it ended up breaking things. 

See the comments from @ jschultz here: https://github.com/chriskiehl/Gooey/commit/4140f8e8e69585d1a421757d1fc1944b6de6bf36 

Feel free to re-open with a passing test suite : )

**Pull request merged**
