### PR TITLE
Update argparse_to_json.py for FileType actions.

### PR DESCRIPTION
**Pull request by changeling**
Add elif is_file(action) to set widget to FileSaver for FileType actions.
Add is_file() function.
Exclude FileType actions from is_standard().

### CODE REVIEW

**Comment by changeling** [comment]
Welp. You know the old saying. Haste makes a mess. Apologies for the previous PR spaghetti. This should do the trick.

Re-adding note regarding https://github.com/chriskiehl/Gooey/issues/377 and its blocking of FileType actions for reference.

**Comment by chriskiehl** [comment]
No worries -- happens all the time ^_^ 

This lgtm. Just one thing, would you mind deleting this line in the same file as part of your pull? https://github.com/chriskiehl/Gooey/pull/386/files#diff-c2a9e315e78b26f3c7b03697a9f06437R279 

It was trying (and failing) to do what your PR is doing. I apparently didn't know how instance checking worked x_x

**Comment by changeling** [comment]
OK, how's that look now?

(And tbh, I would have expected that `==` to have worked as well. Learning something every day. Whee!)

**Comment by chriskiehl** [comment]
Looks good. Thanks for the fix! 👍

**Pull request merged**
