### PR TITLE
fix for argopt / docopt

### LINKED ISSUE #4: Have Gooey work with docopt
Really cool library.

Not so much an issue, more of a feature request:  have Gooey work with or use docopt.

### PR DESCRIPTION
**Pull request by casperdcl**
Apparently didn't like the lambda.
Fixes #4 (using argopt: https://pypi.python.org/pypi/argopt#usage or https://github.com/casperdcl/argopt#usage)

### CODE REVIEW

**Comment by bilderbuchi** [comment]
Wondering why fails_test is defined twice?  Also there are some leftover comments at the bottom, left from debugging perhaps?

**Comment by casperdcl** [comment]
Ah I wanted to ask about the comments: why was it implemented the original way? Just an accident, or some weird work-around for odd behaviour?

By extension I could make the whole filter(c, v), filter(!c, v) tuple a function return value and import the function, but since it wasn't done already I didn't bother... I'll change it if you prefer

**Comment by bilderbuchi** [comment]
well, I'm not the maintainer, so let's wait for him to comment. these were just things that jumped out at me I looked over the code.

**Comment by casperdcl** [comment]
pretty sure this is still relevant. You could look at the link in the original description. `argopt` simply converts modern `docopt` into legacy `argparse`. This means `Gooey` becomes trivially language agnostic.

**Comment by bilderbuchi** [comment]
"legacy" argparse? AFAIK, it's still in the standard library... ;-)

**Comment by casperdcl** [comment]
well `docopt` has been around for ages now and is almost always better than `argparse`. I don't know a single person who uses `argparse` if they know about `docopt`.

The latter lacks a few features such as type checks, but these are added by `argopt`. In fact, `argopt` allows for combining `docopt` with `argparse` (ie define simple things in the docstring, then `parser = argopt.argopt(__doc__, ...)`, then `parser.add_...` for anything more complex.

**Comment by bilderbuchi** [comment]
One point that makes me choose argparse (over docopt or click) is the fact that it is in the standard library (so I have one less dependency), and good enough most of the time. 
I think the choice between different CLI frameworks like argparse, docopt, click, et al., primarily comes down to personal preference. E.g., I don't like the docopt way of prescribing my arguments, although it of course has some advantages.
Anyway, this discussion is kinda tangent to the PR, so I'll leave it at that now.

**Comment by chriskiehl** [comment]
I changed the project out from underneath you : / 

Could you bring it up to date?

**Comment by casperdcl** [comment]
@bilderbuchi I agree that it's probably not a discussion for here, but it should be mentioned that writing a massive CLI from scratch is far easier with `docopt`, which does indeed sacrifice some of the power of `argparse`. Things like `argopt` though allow you to use both. Anyway @chriskiehl will try and rebase later...

**Comment by chriskiehl** [comment]
Guys, guys... both argparse and docopt are good! That _Click_ library, however. Phew.. I mean, right? Guys? 

<sub><sub>(I've never actually used Click and it's probably A-OK) </sub></sub>

**Comment by bilderbuchi** [comment]
:-D next we'll be discussing I'd vi or Emacs is better... :whistle:

**Comment by casperdcl** [comment]
Oh please, real programmers use butterflies

**Comment by casperdcl** [comment]
Seems to be very stale and no longer needed - [`argopt`](https://github.com/casperdcl/argopt) works fine with Gooey now afaik

**Pull request closed without merging**
