### PR TITLE
wxpython 4.0.0a1 and Python 3

### PR DESCRIPTION
**Pull request by arturmiller**
I have updated Gooey to wxpython 4.0.0.a1 and Python 3. Wxpython 4.0.0.a1 is just in an alpha release. The changes are not compatible to wxpython 3 anymore, but they are still compatible to Python 2.

I have tested it with Python 2.7 and 3.5

All examples from https://github.com/chriskiehl/GooeyExamples and the unittests run fine (except for the presentation tests).

@chriskiehl I know it is planned to change the backend to PyQt5. So I understand if this PR is not merged, but nevertheless these changes might be useful for everyone who has to update their software to Python 3.
 
Relevant issue: https://github.com/chriskiehl/Gooey/issues/65

### CODE REVIEW

**Comment by bosbyj** [comment]
Great job!

**Comment by chriskiehl** [comment]
This is awesome. I'm surprised how little wx code had to change. Actually, the changes are so minimal I'd wager both 3 & 4 could be supported with some clever importing and fallbacks. 

Full disclosure, the next major version of Gooey will still be going Qt, but I like the idea of pulling this into the current version of the project so that people who want to use Python 3 and stay in the Wx ecosystem can do so. 

Awesome work! 

Note: my standard "sorry for the delay" notice applies here.. Will get to the actual review merge bit as soon as I can.

**Comment by Hellowlol** [comment]
This would be a awsome improvement.

**Comment by alejandrogallo** [comment]
Is this going to be merged sometime soon ?

**Comment by chriskiehl** [comment]
yes,

**Comment by chriskiehl** [comment]
Merged in dc6386c3a!

**Pull request closed without merging**
