### PR TITLE
Better German translation

### PR DESCRIPTION
**Pull request by jwaschkau**

### CODE REVIEW

**Comment by chriskiehl** [comment]
Merging your other pull created conflicts in this one. Could you bring it up to date?

**Comment by jwaschkau** [comment]
@chriskiehl done

**Comment by chriskiehl** [comment]
hey @jwaschkau, github is still showing conflicts. Could you manually rebase against master and resolve the conflicts? 

Thanks!

**Comment by jwaschkau** [comment]
@chriskiehl i merged from master. Does it work now?

**Comment by chriskiehl** [comment]
Hey @jwaschkau, I brought this pull up to date and manually merged it here: https://github.com/chriskiehl/Gooey/commit/f6270af6db6e664ad0f56dbb0eaf95e351897892. Thanks for the translation! 👍

**Pull request closed without merging**
